baseURL = "http://headat.com.au"
languageCode = "en-us"
title = "Where's Your Head At"
theme = "ananke"
googleAnalytics = "UA-127639828-1"

[params]
    body_classes = "avenir bg-light-gray"
    background_color_class = "bg-mid-gray"
    featured_image = "/images/banner.jpg"       # image nav bar image for home page
    header_image = "/images/banner-narrow.jpg"  # image nav bar image for other pages
    env = "production"
