baseURL = "http://example.org/"
languageCode = "en-us"
title = "Peace In Mind"
theme = "ananke"
[params]
    body_classes = "avenir bg-light-gray"
    background_color_class = "bg-mid-gray"
    featured_image = "/images/banner.jpg"       # image nav bar image for home page
    header_image = "/images/banner_narrow.jpg"  # image nav bar image for other pages
